#!/bin/sh

LOCK_FILE="$HOME/.cache/eww-menu.lock"

run() {
    eww open menu
    eww update menu_show=true
}

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
fi

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    run
else
    eww update menu_show=false && sleep 0.05
    eww close menu
    rm "$LOCK_FILE"
fi
