#!/bin/bash

LOCK_FILE="$HOME/.cache/eww-calendar.lock"

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
else
	if [[ ! -f "$LOCK_FILE" ]]; then
		touch "$LOCK_FILE"
		xdo raise -N eww-calendar
		eww open calendar
		eww update calendar_show=true
	else
		xdo lower -N eww-calendar
		eww update calendar_show=false
		eww close calendar
		rm "$LOCK_FILE"
	fi
fi
