#!/bin/bash

LOCK_FILE="$HOME/.cache/eww-calendar.lock"

run() {
	eww open calendar
	eww update calendar_show=true
}

# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
else
	if [[ ! -f "$LOCK_FILE" ]]; then
		touch "$LOCK_FILE"
		run
	else
		eww update call=false
		sleep 0.075
		eww close calendar
		rm "$LOCK_FILE"
	fi
fi
