#!/bin/bash
RUN_FILE="$HOME/.cache/opening-eww-dashboard.lock"
LOCK_FILE="$HOME/.cache/eww-dashboard.lock"

if [[ -f "$RUN_FILE" ]]; then
        notify-send "You're on cooldown!"
        exit 1
fi

touch $RUN_FILE
# Run eww daemon if not running
if [[ ! `pidof eww` ]]; then
        eww daemon
        sleep 1
fi

if [[ ! -f "$LOCK_FILE" ]]; then
        touch "$LOCK_FILE"
        eww open dashboard
        xdo raise -N eww-dashboard
        eww update dashboard_show=true
else
        eww update dashboard_show=false
        sleep 0.5
        eww close dashboard
        xdo lower -N eww-dashboard
        rm "$LOCK_FILE"
fi
rm $RUN_FILE
