#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
dunst &
picom --daemon

xrandr --output eDP-1 --scale 1.0
xsetroot -cursor_name left_ptr

colors=($(xrdb -get color11) $(xrdb -get color12) $(xrdb -get color13) $(xrdb -get color14))
random_color=${colors[$RANDOM % ${#colors[@]}]}
hsetroot -solid "$random_color" -full $HOME/.local/share/wallpapers/cryonixx/1.png

bspc config border_width  0
bspc config window_gap    10
bspc config split_ratio   0.55

bspc config margin_bottom	  0

bspc config pointer_modifier mod4
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner

bspc config -m primary left_padding 0
bspc monitor -d i ii iii iv v vi vii viii ix

bspc rule -a java-lang-Thread state=floating
