#! /bin/sh

eww open bar &
pgrep -x sxhkd > /dev/null || sxhkd &
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom.conf &

# remove eww cache
rm $HOME/.cache/eww-calendar.lock
rm $HOME/.cache/eww-dashboard.lock

## handle bar
bspc subscribe node_state | while read -r _ _ _ _ state flag; do
    if [ "$state" != "fullscreen" ]; then
        continue
    fi

    if [ "$flag" == on ]; then
        xdo lower -N eww-bar
    else
        xdo raise -N eww-bar
    fi
done &

theme=$(cat $HOME/.config/tdtheme)
hsetroot -solid $(xgetres background) -extend "$HOME/.config/bspwm/assets/$theme.png"

bspc monitor -d                                                   {1..4}

bspc config border_width                                          3
bspc config window_gap                                            12
bspc config split_ratio                                           0.62
bspc config borderless_monocle                                    true

bspc config focused_border_color                                  $(xgetres color12)
bspc config normal_border_color                                   $(xgetres color4)
