#!/bin/sh

make_directories() {
	mkdir -p $HOME/.config/
	mkdir -p $HOME/.cache/
	mkdir -p $HOME/.local/bin/
	mkdir -p $HOME/.local/share/fonts
}

copy_config() {
	cp ./etc/misc/{.Xresources,.xinitrc,.zshrc} $HOME
	cp -r ./etc/fonts/* $HOME/.local/share/fonts
	cp -r ./cfg/* $HOME/.config
	cp -r ./bin/* $HOME/.local/bin 2> /dev/null
}

if [ $(basename $PWD) != tuyudots ]; then
	echo "Not inside tuyudots directory."
	exit 1
fi

make_directories
copy_config
fc-cache
